[package]
name = "vega"
version = "2.0.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
sysinfo = "0.35.1"
libc = "0.2.172"
pci-info = { version = "0.3.2", default-features = false }
pci-ids = { version = "0.2.5", default-features = false }

[build-dependencies]
anyhow = "1.0.98"
